export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>GraphQLZero: A Simple, Zero-Config Fake GraphQL API.</title>
        <meta
          name="description"
          content="GraphQLZero is a free, online GraphQL API that you can use to get fake data from a real backend while testing or prototyping your app."
        />
        <link rel="canonical" href="https://graphqlzero.almansi.me/" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff"></meta>
        <meta name="og:title" content="GraphQLZero" />
        <meta name="og:type" content="software" />
        <meta name="og:url" content="https://graphqlzero.almansi.me/" />
        <meta
          name="og:image"
          content="https://graphqlzero.almansi.me/graphql-image.jpg"
        />
        <meta name="og:site_name" content="GraphQLZero" />
        <meta
          name="og:description"
          content="GraphQLZero is a free, online GraphQL API that you can use to get fake data from a real backend while testing or prototyping your app."
        />
        <meta
          name="google-site-verification"
          content="UCPORh5hdVtXlGIwXOH4DSeRlGLPicaYtUNeHTqg8kA"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
